version: "3.5"

services:

  psql:
    build:
      context: .
      dockerfile: assets/docker/psql.dev.dockerfile
    restart: always
    hostname: psql
    network_mode: bridge
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432

  kafka:
    image: obsidiandynamics/kafka
    network_mode: bridge
    hostname: kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: /src/dist/api users
    network_mode: bridge
    ports:
      - 80:8080
    environment:
      - env=docker
    links:
      - psql
      - kafka
    depends_on:
      - psql
      - kafka